name: Assignment-3-Workflow

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Integration Tests Workflow
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: UserDatabase
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # - name: Start MySQL
      #   run: |
      #     sudo /etc/init.d/mysql start
      #     mysql -h 127.0.0.1 -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DATABASE_USERNAME -p$DATABASE_PASSWORD
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: UserDatabase 
          mysql user: ${{secrets.DATABASE_USERNAME}}
          mysql password: '${{secrets.DATABASE_PASSWORD}}'
     
     
      - name: Build with Maven
        run: mvn -B package --file pom.xml

