name: Application-Testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Integration Tests Workflow
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: UserDatabase
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${{ secrets.SPRING_JPA_HIBERNATE_DDL_AUTO }}
      PUBSUB_PROJECT_ID: ${{ secrets.PUBSUB_PROJECT_ID }}
      PUBSUB_TOPIC_ID: ${{ secrets.PUBSUB_TOPIC_ID }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '${DATABASE_PASSWORD}'; FLUSH PRIVILEGES;"
          mysql -h 127.0.0.1 -u root -p${DATABASE_PASSWORD} -e "CREATE DATABASE IF NOT EXISTS ${DB_DATABASE};"
     
      - name: Build with Maven
        run: mvn -B package --file pom.xml

